<!DOCTYPE html>
<html lang="<?= configuracoes('language'); ?>">

	<head>

		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
		<meta name="description" content="<?= configuracoes('meta_description'); ?>">
		<meta name="keywords" content="<?= configuracoes('meta_keywords'); ?>">
		<meta name="generator" content="<?= configuracoes('meta_generator'); ?>">
		<meta name="author" content="<?= configuracoes('meta_author'); ?>">
		<meta name="DC.creator.address" content="<?= configuracoes('meta_creator_address'); ?>">
		<meta name="custodian" content="<?= configuracoes('meta_custodian'); ?>">
		<meta name="DC.publisher" content="<?= configuracoes('meta_publisher'); ?>">
		<meta name="revisit-after" content="<?= configuracoes('meta_revisit_after'); ?>">
		<meta name="rating" content="<?= configuracoes('meta_rating'); ?>">
		<meta name="robots" content="<?= configuracoes('meta_robots'); ?>">
		<meta name="theme-color" content="<?= configuracoes('theme_color'); ?>">
		<meta name="apple-mobile-web-app-status-bar-style" content="<?= configuracoes('theme_color'); ?>">
		<meta name="msapplication-navbutton-color" content="<?= configuracoes('theme_color'); ?>">
		<meta name="DC.title" content="<?= configuracoes('meta_title'); ?>">

		<title><?= configuracoes('meta_title'); ?></title>

		<noscript>
			<meta http-equiv="Refresh" content="0; url=<?= base_url(); ?>nojs">
		</noscript>

		<?php
		/**
		 * Folhas de estilos
		 */
		require(VIEWSPATH . DS . 'templates' . DS . 'styles.phtml');
		?>

	</head>

	<body class="vertical-layout page-header-light vertical-menu-collapsible vertical-dark-menu preload-transitions 1-column login-bg">

		<?php
		/**
		 * Body
		 */
		require(VIEWSPATH . 'templates' . DS . 'body.phtml');
		?>

		<?php
		/**
		 * Scripts
		 */
		require(VIEWSPATH . DS . 'templates' . DS . 'scripts.phtml');
		?>

	</body>

</html>