<script>
	// const MAIN = '<?=site_url(); ?>';
	// const BASE_URL = '<?= base_url(); ?>';
	// const CURRENT_URL = '<?=$_SERVER['REQUEST_URI']; ?>';
	// const BASE_PATH = '<?=base_path(); ?>';
	// const PROJECT_PATH = '<?=base_path(TRUE); ?>';
	// var element = typeof el !== 'undefined' ? el : ['.editor', '.redactor'];
	// var items = element.toString();
</script>

<!-- plugins | jQuery/Materialize -->
<script src="<?= base_path(); ?>plugins/jquery/jquery.min.js"></script>
<script src="<?= base_path(); ?>plugins/materializecss/materialize.min.js"></script>
<script src="<?= base_path(); ?>plugins/sweetalert/sweetalert.min.js"></script>
<script src="<?= base_path(); ?>plugins/jquery/form.js"></script>

<!-- scripts | Padrão -->
<script src="<?= base_path(); ?>scripts/http/http.js"></script>
<script src="<?= base_path(); ?>scripts/http/request.js"></script>
<script src="<?= base_path(); ?>scripts/form.js"></script>

<!-- 
<script src="<?= base_path(); ?>plugins/vendors/js/prismjs.min.js"></script>
<script src="<?= base_path(); ?>plugins/vendors/js/perfect-scrollbar.min.js"></script>
-->

<script>

$(document).ready(function() {

	Request.init();
	Form.init();

	function resizeble() {

		var index = $('#index');
		var height = $(window).outerHeight();

		index.css({
			'height': height + 'px',
		});

	}

	resizeble();

	$(window).on('resize', function() {

		resizeble();

	});

	$('.sidenav').sidenav();
	$('select').formSelect();

});

</script>