

<!-- BEGIN #index -->
<section id="index" class="flow-text scrollspy">

	<div class="bg-image" style="background-image: url('<?= base_path(); ?>images/bg-site.jpg');"></div>

	<div class="container">

		<div class="row">

			<div class="col s12">
				<h1>Alisson<b>Pereira</b></h1>
			</div>

			<div class="col s12">

				<ul class="collection flow-text blue-text text-darken-2">
					<li>
						<i class="material-icons">email</i>
						alissonguedes87@gmail.com
					</li>
					<li>
						<i class="material-icons">home</i>
						João Pessoa, PB
					</li>
				</ul>

			</div>

		</div>

	</div>

</section>
<!-- END #index -->

<!-- BEGIN #profile -->
<section id="profile" class="blue darken-2 scrollspy">

	<header class="blue darken-3 z-depth-2">
		<h3>
			Perfil
		</h3>
	</header>

	<div class="container center-align z-depth-4">

		<div class="row margin">

			<div class="col s12 profile-image">
				<img src="<?= base_path(); ?>images/perfil/foto.jpg" alt=""
					class="circle responsive-img activator z-depth-3 mt-3">
			</div>

			<div class="col s12">

				<ul class="profile-detail white-text mt-3 mb-3">
					<li>
						<label class="flow-text white-text">Nome</label>
						<div class="value flow-text white-text">
							<p>Alisson Guedes Pereira</p>
						</div>
					</li>
					<li>
						<label class="flow-text white-text">Idade</label>
						<div class="value flow-text">
							<p>
								<?php $nascimento = date('1987-01-18'); ?>
								<?php $idadeAtual = date_diff(date_create(date('Y-m-d')), date_create($nascimento)); ?>
								<?= $idadeAtual -> format('%y'); ?> anos
							</p>
						</div>
					</li>
					<li>
						<label class="flow-text white-text">Naturalidade</label>
						<div class="value flow-text">
							<p>Campina Grande, PB</p>
							<p>Brasil</p>
						</div>
					</li>
					<li>
						<label class="flow-text white-text">Interesses</label>
						<div class="value flow-text">
							<p>Cargos de programador PHP</p>
							<p>Banco de Dados</p>
							<p>Administração de Sistemas e Bancos de Dados</p>
							<p>Desenvolvimento Web e Devops</p>
							<p>Trabalho Remoto</p>
							<p>CLT</p>
							<p>Freelancer</p>
						</div>
					</li>
					<li>
						<label class="flow-text white-text">Habilidades</label>
						<div class="value flow-text">
							<p>DevOps</p>
							<p>Desenvolvedor Web</p>
							<p>Desenvolvedor Mobile</p>
						</div>
					</li>
					<li>
						<label class="flow-text white-text">Sobre mim</label>
						<div class="value flow-text">
							<p>
								Carreira na área de TI desde 2007 com competência acadêmica e experiência
								profissional para atuar
								na administração e criação de redes de computadores, VPN, configuração e administração
								de servidores Linux/Windows,
								análise e desenvovimento de websites e sistemas de gestão, desenvolvendo projetos e
								implementando soluções simples
								ou complexas.
							</p>
						</div>
					</li>
				</ul>

			</div>

		</div>

	</div>

</section>
<!-- END #profile -->

<!-- BEGIN #experience -->
<section id="experience" class="grey lighten-3 scrollspy">

	<header class="grey lighten-2 z-depth-2">
		<h3 class="black-text">
			Experiência Profissional
		</h3>
	</header>

	<div class="container no-padding">

		<div class="row margin">

			<article class="card col s12 no-padding transparent z-depth-0">

				<div class="card-image hide mr-4 mt-3">
					<!-- <img src="<?= base_path(); ?>images/bg-site.jpg" alt="" class="circle z-depth-3"> -->
					<svg class="circle" viewBox="-9 0 50 20">
						<!-- Generator: Sketch 55.2 (78181) - https://sketchapp.com -->
						<title>LogoHDBR_V1</title>
						<desc>Created with Sketch.</desc>
						<g id="Symbols" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
							<g id="LogoHDBR_V1" fill="#FF5800">
								<path
									d="M31.8815863,5.27682774 L29.4636502,4.61831806 C29.2522459,4.54358903 29.0798508,4.66877613 29.0798508,4.89551806 L29.0798508,17.0092858 C29.0798508,17.2360277 29.2522459,17.3605761 29.4636502,17.2864858 L31.8815863,16.6273374 C32.0923614,16.5538858 32.2647565,16.3067052 32.2647565,16.0799632 L32.2647565,5.82420194 C32.2647565,5.59682129 32.0923614,5.35091806 31.8815863,5.27682774"
									id="Fill-17" />
								<path
									d="M2.80173556,4.61812645 L0.383170213,5.27663613 C0.172395137,5.35072645 0,5.59726839 0,5.82401032 L0,16.0797716 C0,16.3065135 0.172395137,16.5536942 0.383170213,16.6277845 L2.80173556,17.2862942 C3.01313982,17.3603845 3.18490578,17.2358361 3.18490578,17.0090942 L3.18490578,4.89596516 C3.18490578,4.66922323 3.01313982,4.54339742 2.80173556,4.61812645"
									id="Fill-19" />
								<path
									d="M27.4275629,3.89121097 L16.5175933,0.0557593548 C16.4118912,0.0187141936 16.2728426,0.000191612911 16.1337939,0.000191612911 C15.9941161,0.000191612911 15.8544383,0.0187141936 15.7487362,0.0557593548 L4.83939574,3.89121097 C4.62862067,3.96594 4.45559635,4.21184323 4.45559635,4.43858516 L4.45559635,7.37217871 C4.45559635,7.59892065 4.63617082,7.75476581 4.85638359,7.71835935 L15.7323775,5.94274645 C15.8424839,5.92486258 15.9878243,5.91592065 16.1337939,5.91592065 C16.2791343,5.91592065 16.4244748,5.92486258 16.5352103,5.94274645 L27.4105751,7.71835935 C27.6307878,7.75476581 27.8107331,7.59892065 27.8107331,7.37217871 L27.8107331,4.43858516 C27.8107331,4.21184323 27.6389672,3.96594 27.4275629,3.89121097"
									id="Fill-21" />
								<path
									d="M27.4103863,14.2093742 L16.5350216,15.9849871 C16.424286,16.0035097 16.2795748,16.0124516 16.132976,16.0124516 C15.9882647,16.0124516 15.8422951,16.0035097 15.7321888,15.9849871 L4.85619483,14.2093742 C4.63661125,14.1729677 4.45603678,14.3294516 4.45603678,14.5561935 L4.45603678,17.4891484 C4.45603678,17.7158903 4.62843191,17.9617935 4.83920699,18.0365226 L15.7498058,21.8726129 C15.8548787,21.9096581 15.9939274,21.9281806 16.132976,21.9281806 C16.273283,21.9281806 16.4123316,21.9096581 16.5180337,21.8726129 L27.4273742,18.0365226 C27.6387784,17.9617935 27.8111736,17.7158903 27.8111736,17.4891484 L27.8111736,14.5561935 C27.8111736,14.3294516 27.6305991,14.1729677 27.4103863,14.2093742"
									id="Fill-23" />
								<path
									d="M27.4066742,9.03486774 L16.5388596,8.01165484 C16.4274948,8.00143548 16.2796377,7.99632581 16.1336681,7.99632581 C15.9870693,7.99632581 15.8398413,8.00143548 15.7284766,8.01165484 L4.86003283,9.03486774 C4.63793252,9.05594516 4.45547052,9.25905484 4.45547052,9.48515806 L4.45547052,12.4181129 C4.45547052,12.6454935 4.63793252,12.8486032 4.86003283,12.8696806 L15.7284766,13.8922548 C15.8398413,13.9031129 15.9870693,13.9082226 16.1336681,13.9082226 C16.2796377,13.9082226 16.4274948,13.9031129 16.5388596,13.8922548 L27.4066742,12.8696806 C27.6294036,12.8486032 27.8112365,12.6454935 27.8112365,12.4181129 L27.8112365,9.48515806 C27.8112365,9.25905484 27.6294036,9.05594516 27.4066742,9.03486774"
									id="Fill-26" />
							</g>
						</g>
					</svg>
				</div>

				<div class="card-content">

					<div class="card-header">
						<div class="card-title">
							<h3 class="uppercase">
								Analista de suporte técnico
								<br>
								<small>Dimenoc Serviços de Informática LTDA</small>
							</h3>
						</div>
						<div class="card-date">
							Ago, 2019
						</div>
					</div>
					<div class="card-body">
						<ul class="card-badges">
							<li>service desk</li>
							<li>sysadmin</li>
							<li>command-line</li>
						</ul>
						<ul class="card-details">
							<li>
								<i class="material-icons">
									chevron_right
								</i>
								<span class="text">
									Suporte técnico, gerenciamento e administração de servidores
								</span>
							</li>
							<li>
								<i class="material-icons">
									chevron_right
								</i>
								<span class="text">
									Desenvolvimento de scripts em bash
								</span>
							</li>
							<li>
								<i class="material-icons">
									chevron_right
								</i>
								<span class="text">
									Correção e atualização de serviços
								</span>
							</li>
						</ul>
					</div>

				</div>

			</article>

		</div>

		<div class="row margin">

			<article class="card col s12 no-padding transparent z-depth-0">

				<div class="card-image hide mr-4 mt-3">
					<img src="<?= base_path(); ?>images/bg-site.jpg" alt="" class="circle z-depth-3">
				</div>

				<div class="card-content">

					<div class="card-header">
						<div class="card-title">
							<h3 class="uppercase">
								Técnico de Informática
								<br>
								<small>UNIFACISA - Centro Universitário</small>
							</h3>
						</div>
						<div class="card-date">
							Jun, 2018
						</div>
					</div>
					<div class="card-body">
						<ul class="card-badges">
							<li>redes</li>
							<li>infraestrutura</li>
							<li>suporte</li>
							<li>manutenção</li>
						</ul>
						<ul class="card-details">
							<li>
								<i class="material-icons">
									chevron_right
								</i>
								<span class="text">
									Suporte e manutenção de computadores e periféricos
								</span>
							</li>
							<li>
								<i class="material-icons">
									chevron_right
								</i>
								<span class="text">
									Montagem de ambientes para treinamentos e aulas
								</span>
							</li>
							<li>
								<i class="material-icons">
									chevron_right
								</i>
								<span class="text">
									Infraestrutura e redes
								</span>
							</li>
						</ul>
						<ul class="card-tags">
						</ul>
					</div>

				</div>

			</article>

		</div>

		<div class="row margin">

			<article class="card col s12 no-padding transparent z-depth-0">

				<div class="card-image hide mr-4 mt-3">
					<img src="<?= base_path(); ?>images/bg-site.jpg" alt="" class="circle z-depth-3">
				</div>

				<div class="card-content">

					<div class="card-header">
						<div class="card-title">
							<h3 class="uppercase">
								Técnico de Informática
								<br>
								<small>SToledo Agência Web</small>
							</h3>
						</div>
						<div class="card-date">
							Fev, 2017
						</div>
					</div>
					<div class="card-body">
						<ul class="card-badges">
							<li>html</li>
							<li>css</li>
							<li>php</li>
							<li>mysql</li>
						</ul>
						<ul class="card-details">
							<li>
								<i class="material-icons">
									chevron_right
								</i>
								<span class="text">
									Suporte e gerenciamento de servidor
								</span>
							</li>
							<li>
								<i class="material-icons">
									chevron_right
								</i>
								<span class="text">
									Programação e desenvolvimento de Websites </span>
							</li>
							<li>
								<i class="material-icons">
									chevron_right
								</i>
								<span class="text">
									Suporte técnico
								</span>
							</li>
						</ul>
					</div>

				</div>

			</article>

		</div>

		<div class="row margin">

			<article class="card col s12 no-padding transparent z-depth-0">

				<div class="card-image hide mr-4 mt-3">
					<img src="<?= base_path(); ?>images/bg-site.jpg" alt="" class="circle z-depth-3">
				</div>

				<div class="card-content">

					<div class="card-header">
						<div class="card-title">
							<h3 class="uppercase">
								Auxiliar de Informática
								<br>
								<small>Renacar Automóveis LTDA</small>
							</h3>
						</div>
						<div class="card-date">
							Out, 2013
						</div>
					</div>
					<div class="card-body">
						<ul class="card-badges">
							<li>infraestrutura</li>
							<li>redes</li>
							<li>banco de dados</li>
							<li>command-line</li>
							<li>suporte</li>
						</ul>
						<ul class="card-details">
							<li>
								<i class="material-icons">
									chevron_right
								</i>
								<span class="text">
									Auxiliar de informática e administração de servidor
								</span>
							</li>
							<li>
								<i class="material-icons">
									chevron_right
								</i>
								<span class="text">
									Suporte técnico por telefone, e-mail, chamados, acesso remoto e local
								</span>
							</li>
						</ul>
					</div>

				</div>

			</article>

		</div>

		<div class="row margin">

			<article class="card col s12 no-padding transparent z-depth-0">

				<div class="card-image hide mr-4 mt-3">
					<img src="<?= base_path(); ?>images/bg-site.jpg" alt="" class="circle z-depth-3">
				</div>

				<div class="card-content">

					<div class="card-header">
						<div class="card-title">
							<h3 class="uppercase">
								Atendente Técnico
								<br>
								<small>Chame O Gênio Logística LTDA</small>
							</h3>
						</div>
						<div class="card-date">
							Jun, 2011
						</div>
					</div>
					<div class="card-body">
						<ul class="card-badges">
							<li>atendimento</li>
							<li>suporte</li>
						</ul>
						<ul class="card-details">
							<li>
								<i class="material-icons">
									chevron_right
								</i>
								<span class="text">
									Auxiliar no atendimento pós-vendas
								</span>
							</li>
							<li>
								<i class="material-icons">
									chevron_right
								</i>
								<span class="text">
									Conferir junto ao cliente a integridade física e lógica de eletroeletrônicos
									após a compra
								</span>
							</li>
							<li>
								<i class="material-icons">
									chevron_right
								</i>
								<span class="text">
									Conferir itens e produtos para realização de trocas dentro dos prazos
									estabelecidos pelo CDC
								</span>
							</li>
							<li>
								<i class="material-icons">
									chevron_right
								</i>
								<span class="text">
									Orientar a utilização de produtos para o cliente e esclarecer dúvidas
								</span>
							</li>
						</ul>
					</div>

				</div>

			</article>

		</div>

	</div>

</section>
<!-- END #experience -->

<!-- BEGIN #technology -->
<section id="technology" class="blue-grey darken-1 scrollspy">

	<header class="blue-grey darken-2 z-depth-3">
		<h3 class="white-text">
			Tecnologias
		</h3>
	</header>

	<div class="container z-depth-3 pb-3">

		<article>

			<div class="row margin">
				<div class="col">
					<h4>Linguagens</h4>
				</div>
			</div>

			<div class="row margin">

				<div class="col s6 m2">
					<div class="card z-depth-3 no-padding border-radius-5">
						<div class="card-content no-padding">
							<div class="card-body red accent-4">
								<img src="<?= base_path(); ?>images/tecnologias/html5.png" alt="">
							</div>
							<div class="card-action">
								HTML5
							</div>
						</div>
					</div>
				</div>
				<div class="col s6 m2">
					<div class="card z-depth-3 no-padding border-radius-5">
						<div class="card-content no-padding">
							<div class="card-body blue accent-4">
								<img src="<?= base_path(); ?>images/tecnologias/css3.png" alt="">
							</div>
							<div class="card-action">
								CSS
							</div>
						</div>
					</div>
				</div>
				<div class="col s6 m2">
					<div class="card z-depth-3 no-padding border-radius-5">
						<div class="card-content no-padding">
							<div class="card-body indigo lighten-2">
								<img src="<?= base_path(); ?>images/tecnologias/php.png" alt="">
							</div>
							<div class="card-action">
								PHP
							</div>
						</div>
					</div>
				</div>
				<div class="col s6 m2">
					<div class="card z-depth-3 no-padding border-radius-5">
						<div class="card-content no-padding">
							<div class="card-body" style="background-color: #f7df1e;">
								<img src="<?= base_path(); ?>images/tecnologias/js.png" alt="">
							</div>
							<div class="card-action">
								JavaScript
							</div>
						</div>
					</div>
				</div>

			</div>

		</article>

		<article>

			<div class="row margin">
				<div class="col">
					<h4>Frameworks</h4>
				</div>
			</div>

			<div class="row margin">

				<div class="col s6 m2">
					<div class="card z-depth-3 no-padding border-radius-5">
						<div class="card-content no-padding">
							<div class="card-body white">
								<img src="<?= base_path(); ?>images/tecnologias/codeigniter.png" alt="">
							</div>
							<div class="card-action">
								CodeIgniter
							</div>
						</div>
					</div>
				</div>
				<div class="col s6 m2">
					<div class="card z-depth-3 no-padding border-radius-5">
						<div class="card-content no-padding">
							<div class="card-body">
								<img src="<?= base_path(); ?>images/tecnologias/angular.png" alt="">
							</div>
							<div class="card-action">
								Angular
							</div>
						</div>
					</div>
				</div>
				<div class="col s6 m2">
					<div class="card z-depth-3 no-padding border-radius-5">
						<div class="card-content no-padding">
							<div class="card-body">
								<img src="<?= base_path(); ?>images/tecnologias/ionic.png" alt="">
							</div>
							<div class="card-action">
								Ionic
							</div>
						</div>
					</div>
				</div>

			</div>

		</article>

		<article>

			<div class="row margin">
				<div class="col">
					<h4>Ferramentas</h4>
				</div>
			</div>

			<div class="row margin">

				<div class="col s6 m2">
					<div class="card z-depth-3 no-padding border-radius-5">
						<div class="card-content no-padding">
							<div class="card-body" style="background-color: #f7df1e;">
								<img src="<?= base_path(); ?>images/tecnologias/js.png" alt="">
							</div>
							<div class="card-action">
								NodeJS
							</div>
						</div>
					</div>
				</div>
				<div class="col s6 m2">
					<div class="card z-depth-3 no-padding border-radius-5">
						<div class="card-content no-padding">
							<div class="card-body">
								<img src="<?= base_path(); ?>images/tecnologias/vscode.png" alt="">
							</div>
							<div class="card-action">
								VSCode
							</div>
						</div>
					</div>
				</div>
				<div class="col s6 m2">
					<div class="card z-depth-3 no-padding border-radius-5">
						<div class="card-content no-padding">
							<div class="card-body">
								<img src="<?= base_path(); ?>images/tecnologias/sublime.png" alt="">
							</div>
							<div class="card-action">
								Sublime
							</div>
						</div>
					</div>
				</div>

			</div>

		</article>

		<article>

			<div class="row margin">
				<div class="col">
					<h4>Sistemas Operacionais</h4>
				</div>
			</div>

			<div class="row margin">
				<div class="col s6 m2">
					<div class="card z-depth-3 no-padding border-radius-5">
						<div class="card-content no-padding">
							<div class="card-body">
								<img src="<?= base_path(); ?>images/tecnologias/ubuntu.png" alt="">
							</div>
							<div class="card-action">
								Ubuntu
							</div>
						</div>
					</div>
				</div>
				<div class="col s6 m2">
					<div class="card z-depth-3 no-padding border-radius-5">
						<div class="card-content no-padding">
							<div class="card-body">
								<img src="<?= base_path(); ?>images/tecnologias/centos.png" alt="">
							</div>
							<div class="card-action">
								CentOS
							</div>
						</div>
					</div>
				</div>
				<div class="col s6 m2">
					<div class="card z-depth-3 no-padding border-radius-5">
						<div class="card-content no-padding">
							<div class="card-body">
								<img src="<?= base_path(); ?>images/tecnologias/debian.png" alt="">
							</div>
							<div class="card-action">
								Debian
							</div>
						</div>
					</div>
				</div>
				<div class="col s6 m2">
					<div class="card z-depth-3 no-padding border-radius-5">
						<div class="card-content no-padding">
							<div class="card-body">
								<img src="<?= base_path(); ?>images/tecnologias/redhat.png" alt="">
							</div>
							<div class="card-action">
								RedHat
							</div>
						</div>
					</div>
				</div>
				<div class="col s6 m2">
					<div class="card z-depth-3 no-padding border-radius-5">
						<div class="card-content no-padding">
							<div class="card-body">
								<img src="<?= base_path(); ?>images/tecnologias/windows.png" alt="">
							</div>
							<div class="card-action">
								Windows
							</div>
						</div>
					</div>
				</div>

			</div>

		</article>

	</div>

</section>
<!-- END #expetechnologyrience -->

<!-- BEGIN #contact -->
<section id="contact" class="grey lighten-3 scrollspy">

	<header class="grey lighten-2 z-depth-2">
		<h3 class="black-text">
			Contato
		</h3>
	</header>

	<div class="row margin">

		<div class="container mt-4 mb-4">

			<div class="col s12">

				<div class="row margin">

					<div class="form col s12 m6">

						<div class="card bg-opacity-8 border-radius-8">

							<div class="card-content">

								<form novalidate action="#" method="post" autocomplete="off">

									<div class="row margin">
										<div class="col s12">
											<div class="input-field">
												<i class="material-icons prefix">person</i>
												<label for="nome">Nome</label>
												<input type="text" name="nome" id="nome" class="" required="required">
											</div>
										</div>
									</div>

									<div class="row margin">
										<div class="col s12">
											<div class="input-field">
												<i class="material-icons prefix">mail</i>
												<label for="email">E-mail</label>
												<input type="email" name="email" id="email" class=""
													required="required">
											</div>
										</div>
									</div>

									<div class="row margin">
										<div class="col s12">
											<div class="input-field">
												<i class="material-icons prefix">subject</i>
												<label for="assunto">Assunto</label>
												<input type="text" name="assunto" id="assunto" class=""
													required="required">
											</div>
										</div>
									</div>

									<div class="row margin">
										<div class="col s12">
											<div class="input-field">
												<i class="material-icons prefix">message</i>
												<label for="mensagem">Mensagem</label>
												<textarea name="mensagem" id="mensagem" class="materialize-textarea"
													required="required"></textarea>
											</div>
										</div>
									</div>

									<div class="row margin">
										<div class="col s12 mb-3">
											<div class="input-field">
												<button type="submit"
													class="col btn btn-large waves-effect waves-light right">
													enviar
													<i class="material-icons margin-left">
														send
													</i>
												</button>
											</div>
										</div>
									</div>

								</form>

							</div>

						</div>

					</div>

					<div class="social col s12 m6">

						<ul class="blue-grey-text text-darken-1">

							<li>
								<a href="#">
									<i class="material-icons">face</i>
									<span>@github</span>
								</a>
							</li>
							<li>
								<a href="#">
									<i class="material-icons">face</i>
									<span>@npm</span>
								</a>
							</li>
							<li>
								<a href="#">
									<i class="material-icons">face</i>
									<span>@linkedin</span>
								</a>
							</li>
							<li>
								<a href="#">
									<i class="material-icons">face</i>
									<span>@instagram</span>
								</a>
							</li>
							<li>
								<a href="#">
									<i class="material-icons">face</i>
									<span>@facebook</span>
								</a>
							</li>

						</ul>

					</div>

				</div>

			</div>

		</div>

	</div>

</section>
<!-- END #contact -->