<div class="row">

	<div class="col s12">

		<div class="container">

			<div id="login-page" class="row">

				<div class="col s12 m6 l3 z-depth-4 card-panel border-radius-6 login-card bg-opacity-8">

					<div class="row">
						<div class="input-field col s12 center-align">
							<button type="button" id="btn-voltar" class="btn btn-floating left transparent z-depth-0">
								<i class="material-icons grey-text text-darken-4">keyboard_arrow_left</i>
							</button>
							<p><?= $page_title ?></p>
							<h5><?= configuracoes('meta_title'); ?></h5>
						</div>
					</div>

					<form novalidate id="frm-login" class="login-form" action="<?= base_url(); ?>login" method="post"
						enctype="multipart/form-data" autocomplete="off">

						<div class="form">

							<div id="input-login" class="slow">
								<div class="row">
									<div class="col s12">
										<div class="input-field">
											<i class="material-icons prefix">person</i>
											<input type="email" name="login" id="login" autofocus="autofocus">
											<label for="login"> <?= traduzir('label_username', 'Usuário'); ?> </label>
										</div>
									</div>

									<div class="col s12">
										<button type="button" id="relembrar_login" name="relembrar_login"
											class="btn btn-flat pl-0 pr-0 transparent left">
											<?= traduzir('relembrar_login', 'Esqueci meu login'); ?>
										</button>
									</div>

								</div>
							</div>

							<div id="input-pass" class="slow">
								<div class="row">
									<div class="col s12">
										<div class="input-field">
											<i class="material-icons prefix">lock</i>
											<input type="password" name="pass" id="pass" disabled="disabled"
												minlength="5">
											<label for="pass"> <?= traduzir('label_password', 'Senha'); ?> </label>
										</div>
									</div>

									<div class="col s12">
										<button type="button" id="relembrar_senha" name="relembrar_senha"
											class="btn btn-flat pl-0 pr-0 transparent right">
											<?= traduzir('relembrar_senha', 'Esqueci minha senha'); ?>
										</button>
									</div>

								</div>
							</div>

						</div>

						<div class="row">
							<div class="col s12">

								<button type="submit" id="entrar" name="entrar"
									class="btn btn-large waves-effect waves-light indigo col right next">
									<?= traduzir('btn_entrar', 'Próxima'); ?>
									<i class="material-icons margin-left">input</i>
								</button>

							</div>
						</div>

						<input type="hidden" name="acao" value="login">
						<input type="hidden" name="_method" value="<?= $method; ?>">

					</form>

				</div>

			</div>

		</div>

	</div>

</div>