<!-- fonts -->
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>fonts/material-icons/material-icons.css">
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>fonts/muli/muli.css">
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>fonts/roboto/roboto.css">
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>fonts/icons/icons.css">

<!-- styles -->
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/vendors.css">
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/animate.css">
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/materializecss/materialize.min.css">

<!-- others styles -->
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>styles/style.css">
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>styles/colors.css">
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>styles/main/themes/default.css">