<!-- CONTENT -->
<section class="center-align" id="main">

	<h1>Página Administrativa</h1>

	<p> Se você consegue visualizar esta página, é porque uma sessão foi criada com sucesso!</p>

	<p>O formulário está funcionando como esperado.</p>

	<p>Agora, por favor, tente navegar para outras páginas para verificar se os links estão funcionando corretamente.</p>

	<p>
	<a data-href="<?= base_url(); ?>welcome">Ir para a segunda página</a>
	</p>

</section>