<!-- CONTENT -->
<section class="center-align">

	<h1>Página Welcome</h1>

	<p>Como você chegou até aqui?</p>

	<p>
		O link lhe redirecionou de form <b>assíncrona</b> ou a página realizou um <b>refresh</b>?
	</p>

	<p>Esperamos que as duas formas funcionem, porém, o ideal é utilizar a forma <b>assíncrona</b>.</p>

	<p>
	<a href="<?= base_url(); ?>home" target="_self">Ir para a página inicial</a>
	</p>

</section>