<aside class="sidenav-main nav-expanded nav-lock nav-collapsible sidenav-light sidenav-active-rounded">

	<div class="brand-sidebar blue lighten-1">
		<h1 class="logo-wrapper margin">
			<a href="{+ base_url +}" class="brand-logo white-text">
				<span class="thin">Alisson</span><span class="bold">PG</span>
			</a>
		</h1>
		<p>DevOps & Desenvolvedor Web</p>
	</div>

	<ul id="slide-out" class="sidenav sidenav-collapsible leftside-navigation collapsible sidenav-fixed menu-shadow">
		<li>
			<a href="#index" class="waves-effect waves-blue blue-text text-darken-2">
				<i class="material-icons">home</i>
				Início
			</a>
		</li>
		<li>
			<a href="#profile" class="waves-effect waves-blue blue-text text-darken-2">
				<i class="material-icons">person</i>
				Perfil
			</a>
		</li>
		<li>
			<a href="#experience" class="waves-effect waves-blue blue-text text-darken-2">
				<i class="material-icons">stars</i>
				Experiências
			</a>
		</li>
		<li>
			<a href="#technology" class="waves-effect waves-blue blue-text text-darken-2">
				<i class="material-icons">memory</i>
				Tecnologias
			</a>
		</li>
		<li>
			<a href="#portfolio" class="waves-effect waves-blue blue-text text-darken-2">
				<i class="material-icons">folder_special</i>
				Portifólio
			</a>
		</li>
		<li>
			<a href="#contact" class="waves-effect waves-blue blue-text text-darken-2">
				<i class="material-icons">alternate_email</i>
				Contato
			</a>
		</li>
	</ul>

	<a href="#" data-target="slide-out" class="sidenav-trigger hide-on-large-only" style="border-radius: 28px; background: rgba(255, 255, 255, 0.5); margin: 10px;">
		<i class="material-icons">menu</i>
	</a>

</aside>
